### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by flxholle** [HenryQuan/HabitApp#6]
Hi @HenryQuan 
I am currently testing your app and I like the habit system of the 2 minutes.
Moreover as far as I know you app does not contain any proprietary libraries like firebase, crashlytics, etc.
So how about adding this app to f-droid?
If you need help with the metadata I could do this for you.

**Comment by HenryQuan** [comment]
Hi, I have heard about f-droid but what exactly does it do? Currently, it is only on Google Play store in the beta stage.

**Comment by flxholle** [comment]
Hi,
"F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform."
This means that f-droid only contains open-source apps, that do not contain any proprietary data, e.g. libraries or executable .jar files.
Furthermore, f-droid downloads the source code and compiles the app on their own server with their own signing to guarantee that the app is trustful.
Moreover f-droid has been created to provide a list of open-source applications with good privacy standards.
That means, if you send any data through an open-source library you need to create a so called "Anti-Flag". E.g. every custom youtube client has this flag.
More: https://f-droid.org/ and https://f-droid.org/en/docs/Inclusion_Policy/

**Comment by HenryQuan** [comment]
Hi, thank you for all the info. I think all my apps don't really track my users and I only receive some data from Google Play Store. I may add IAP or maybe some donation links in the future and that should be fine according to the policy, right?

**Comment by flxholle** [comment]
Hi, I do not know what IAP stands for, but if this library is not part of the google play services and not proprietary it is totally fine.
In #5 an app description is in progress, so if you have written one, you can reuse this for f-droid, if you save it in a fastlane file structure: https://gitlab.com/snippets/1895688 (same for screenshots and featureGraphic)

If you want to add your app to f-droid yourself, you can follow these guides:
  https://gitlab.com/fdroid/fdroiddata/-/blob/master/CONTRIBUTING.md
  https://nikhiljha.com/posts/flutteronfdroid/
Otherwise I can try to create the metadata for you, but as mentioned in the second link an extra f-droid build flavor needs to be added to the app gradle file.

**Comment by HenryQuan** [comment]
Sorry for the late reply, I was suddenly really busy this week. I think f-droid. I will use it after the app is more complete.
