### ISSUE TITLE
Timer too fast

### ISSUE THREAD

**Issue by flxholle** [HenryQuan/HabitApp#7]
On my device (Android 10, sdk 29) the timer when I start a habit counts down from 120 to 0 in about 5 seconds.
I can make a screen record, if you need one.

**Comment by flxholle** [comment]
Ok I compiled the master branch myself, where this error exists.
Now I installed the apk from the release tags and the timer works correctly.
As I am not used to flutter, I do not know if this is a bug :wink:

**Comment by HenryQuan** [comment]
Thank you for reporting this. I adjusted the speed just for debugging because I don't want to wait a minute every time. You can change 5 to 60 to make it a full minute.
